// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhom19_GameHoiLaDap.Data;

#nullable disable

namespace Nhom19_GameHoiLaDap.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20250529114437_AddCauHoi")]
    partial class AddCauHoi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nhom19_GameHoiLaDap.Models.CauHoi", b =>
                {
                    b.Property<int>("CauHoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CauHoiId"));

                    b.Property<string>("DapAnDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnSai1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnSai2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnSai3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoKho")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CauHoiId");

                    b.ToTable("CauHois");
                });

            modelBuilder.Entity("Nhom19_GameHoiLaDap.Models.KetQua", b =>
                {
                    b.Property<int>("KetQuaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KetQuaId"));

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<int>("NguoiChoiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("KetQuaId");

                    b.HasIndex("NguoiChoiId");

                    b.ToTable("KetQuas");
                });

            modelBuilder.Entity("Nhom19_GameHoiLaDap.Models.NguoiChoi", b =>
                {
                    b.Property<int>("NguoiChoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiChoiId"));

                    b.Property<int>("DiemCaoNhat")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguoiChoiId");

                    b.ToTable("NguoiChois");
                });

            modelBuilder.Entity("Nhom19_GameHoiLaDap.Models.KetQua", b =>
                {
                    b.HasOne("Nhom19_GameHoiLaDap.Models.NguoiChoi", "NguoiChoi")
                        .WithMany("KetQuas")
                        .HasForeignKey("NguoiChoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiChoi");
                });

            modelBuilder.Entity("Nhom19_GameHoiLaDap.Models.NguoiChoi", b =>
                {
                    b.Navigation("KetQuas");
                });
#pragma warning restore 612, 618
        }
    }
}
